version: "1.0"
type: component
data:
  name: omv-services-timeshift-settings-form-page
  type: formPage
  config:
    request:
      service: Timeshift
      get:
        method: getSettings
      post:
        method: setSettings
    fields:
      - type: select
        name: backupdev
        label: _("Backup device")
        textField: description
        valueField: uuid
        store:
          proxy:
            service: Timeshift
            get:
              method: getBackupDeviceList
        hint: _("Backup destination device")
      - type: checkbox
        name: stopcronemail
        label: _("Stop cron email")
        value: false
      - type: numberInput
        name: monthly
        label: _("Monthly")
        value: 0
        validators:
          min: 0
          max: 999
          required: true
        hint: _("Set to zero to disable")
      - type: numberInput
        name: weekly
        label: _("Weekly")
        value: 0
        validators:
          min: 0
          max: 999
          required: true
        hint: _("Set to zero to disable")
      - type: numberInput
        name: daily
        label: _("Daily")
        value: 3
        validators:
          min: 0
          max: 999
          required: true
        hint: _("Set to zero to disable")
      - type: numberInput
        name: hourly
        label: _("hourly")
        value: 0
        validators:
          min: 0
          max: 999
          required: true
        hint: _("Set to zero to disable")
      - type: numberInput
        name: boot
        label: _("Boot")
        value: 0
        validators:
          min: 0
          max: 999
          required: true
        hint: _("Set to zero to disable")
      - type: textarea
        name: exclude
        label: _("Excludes")
        value: "/srv/**,/home/**,/root/**"
        rows: 5
        hint: _("Use , or ; or new line to separate entries.  Will be converted to comma separated.<br/>Use trailing ** to match anything, including slashes.<br/>Use trailing *** will match both the directory and everything in the directory.<br/>See <a href='https://linux.die.net/man/1/rsync' target=_blank>rsync manual</a> for additional explanation of filters.")
    buttons:
      - template: submit
